Fixes so that maven can compile the web module (ie, not just sbt which worked, but mvn didn't):
1- Remove "static" line from pom (error in use of example), to fix the error:
  [ERROR] /home/lacall/proj/om/web/target/routes/main/router/Routes.scala:21: type Application is not a member of package controllers
  [ERROR]   Application_0: controllers.Application,
  [ERROR]                              ^
  [ERROR] /home/lacall/proj/om/web/target/routes/main/router/Routes.scala:30: type Application is not a member of package controllers
  [ERROR]     Application_0: controllers.Application
  [ERROR]                                ^
  .
2- Remove references to aspectj: it was getting a bunch of errors,
   and has not been used enough to justify its overhead.

3- **NOTE**: I also had to remove jdk7 from my system, since there was some kind of incompatibility with
   build versions in the java.concurrent package, so JAVA *8* IS NOW REQUIRED (or at least likely enough
   that it's probably safer now to say so).  Here is the error I was getting, which removing jdk7 fixed:
     [ERROR] missing or invalid dependency detected while loading class file 'HandlerInvokerFactory.class'.
     Could not access type CompletionStage in package java.util.concurrent,
     because it (or its dependencies) are missing. Check your build definition for
     missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
     A full rebuild may help if 'HandlerInvokerFactory.class' was compiled against an incompatible version of java.util.concurrent.
  .